import type { Metadata } from 'next';
import {
  Changa,
  Martian_Mono,
  Jersey_15,
  Monoton,
  Rubik_Moonrocks,
  Dela_Gothic_One,
  Micro_5,
  Jockey_One,
  DotGothic16,
  Press_Start_2P,
  VT323,
  Orbitron,
  IBM_Plex_Mono
} from 'next/font/google';
import './globals.css';

const inter = Orbitron({ weight: '600' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full h-full`}>{children}</body>
    </html>
  );
}
