import type { Metadata } from 'next';
import { Martian_Mono } from 'next/font/google';
import './globals.css';

const inter = Martian_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full h-full`}>{children}</body>
    </html>
  );
}
